server:
  port: 8081
spring:
  application:
    name: test_back_comment
  datasource:
    url: jdbc:mysql://mysql:3306/test_comment?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true